
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataTier.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class certificatedetail
{

    public int IdCertificateDetail { get; set; }

    public int IdCertificate { get; set; }

    public int IdCertificateArticles { get; set; }

    public int Quantity { get; set; }

    public decimal TotalCost { get; set; }

    public decimal UnitCost { get; set; }



    public virtual certificate certificate { get; set; }

    public virtual certificatearticle certificatearticle { get; set; }

}

}
