//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public certificate()
        {
            this.certificatedetails = new HashSet<certificatedetail>();
        }
    
        public int IdCertificate { get; set; }
        public int IdWork { get; set; }
        public int IdCertificateType { get; set; }
        public string CertificateNumber { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal WorkProgress { get; set; }
        public System.DateTime ModificationDate { get; set; }

        public virtual certificatetype certificatetype { get; set; }
        public virtual work work { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<certificatedetail> certificatedetails { get; set; }
    }
}
