//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneymovementtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public moneymovementtype()
        {
            this.moneymovements = new HashSet<moneymovement>();
        }
    
        public int IdMoneyMovementType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public sbyte Sign { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moneymovement> moneymovements { get; set; }
    }
}
