//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneymovement
    {
        public int IdMoneyMovement { get; set; }
        public decimal Amount { get; set; }
        public int IdWork { get; set; }
        public int IdMoneyMovementType { get; set; }
    
        public virtual moneymovementtype moneymovementtype { get; set; }
        public virtual work work { get; set; }
    }
}
