
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataTier.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class work
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public work()
    {

        this.assignedemployees = new HashSet<assignedemployee>();

        this.assignedtools = new HashSet<assignedtool>();

        this.certificates = new HashSet<certificate>();

        this.moneymovements = new HashSet<moneymovement>();

        this.receipts = new HashSet<receipt>();

    }


    public int IdWork { get; set; }

    public string Name { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<System.DateTime> FinishDate { get; set; }

    public System.DateTime PossibleEndDate { get; set; }

    public string Description { get; set; }

    public int IdLocation { get; set; }

    public int IdWorkType { get; set; }

    public int IdClient { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<assignedemployee> assignedemployees { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<assignedtool> assignedtools { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<certificate> certificates { get; set; }

    public virtual client client { get; set; }

    public virtual location location { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<moneymovement> moneymovements { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<receipt> receipts { get; set; }

    public virtual worktype worktype { get; set; }

}

}
